title: RITSEC
author:
  name: RITSEC
  email: ritsecclub@gmail.com

social_links:
  github: ritsec
  facebook: RITSEC
  twitter: ritsecclub
  instagram: _ritsec_
  youtube: RITSEC
  discord: W7NefdyzHZ

plugins:
  - jekyll-seo-tag
