---
#-------------------------------
# General Site Settings

title: RITSEC
title_long: RITSEC Student Computing Security Club
motto: Security Through Community
email: ritsecclub@gmail.com
description: >
  RITSEC Student Computing Security Club
twitter: RITSECclub
github:
  name: ritsec
  project: ritsec.github.io
facebook_page: RITSEC
facebook_group: RITSEC.group
youtube: UCfakBry_pXOvaPrVVr1SH-Q
instagram: _ritsec_

#-------------------------------
# Main Image Slider Settings
slider:
  - image: ists_ultra.jpg
  - image: ISTS_0.jpg
  - image: ists_intro.jpg
  #- image: cfe.jpg
  - image: IRSeC2019_photo.jpg
  - image: pwnboard.jpg
  - image: ists_arrest.jpg
  - image: irsec_intro.jpg
  #- image: ists_halo.jpg
  #- image: ISTS_1.jpg
  #- image: ISTS_2.jpg
  #- image: ISTS_4.jpg
#-------------------------------
# Navbar Settings
favicon: favicon.png
navbar-brand:
  image: logo_header.png
  link: "/index.html"

navbar:
  - name: "Home"
    link: "index.html"
  - name: "About"
    link: "about.html"
  - name: Members
    link: "eboard.html"
    subitems:
      - name: "EBoard"
        link: "eboard.html"
      - name: "Past EBoards"
        link: "past-eboards.html"
      - name: "Alumni"
        link: "alumni.html"
      - name: "Donors"
        link: "donors.html"
  - name: "Events"
    link: "events.html"
    subitems:
       - name: "Events"
         link: "events.html"
       - name: "Newsletters"
         link: "newsletters.html"


  - name: "Resources"
    link: "resources.html"
  - name: "Sponsors"
    link: "sponsors.html"
    subitems:
      - name: "Current Sponsors"
        link: "sponsors.html"
      - name: "Sponsorship Opportunities"
        link: "sponsorship.pdf"
  - name: "Links"
    link: "links.html"

#-------------------------------
# EBoard Settings

eboard_roles:
  - name: President
    appointee: Enzo DeStephano
    image: EnzoBioPic.jpg
    contact: "ead4635[at]rit.edu / ritsecclub[at]gmail.com"
    description: Enzo is a fourth-year Computing Security student. He loves Windows offensive security, especially in red/blue competitions. 
  - name: Director of Public Relations
    appointee: Bradley Harker
    image: BradBioPic.jpg
    contact: "bdh9046[at]rit.edu / ritsecclub[at]gmail.com"
    description: Bradley is a second-year Computing Security student. He loves web development and DevOps. He has been working on developing the cyber competition automation software, LaForge, on co-op. In his free time, he enjoys reading a great sci-fi novel and cooking.
  - name: Head of Education
    appointee: Brayden Werner
    image: BraydenBioPic.jpg
    contact: bjw5517[at]rit.edu
    description: Brayden is a third-year Computing Security Student who has an interest in wireless security and blue teaming. This summer, Brayden co-oped at Security Risk Advisors working in a SOC. In his free time, Brayden enjoys simracing, playing guitar, and swimming.
  - name: Head of Research
    appointee: Tenchi Mata
    image: TenchiBioPic.jpg
    contact: ttm3669[at]rit.edu
    description: Tenchi is a third-year Computing Security student who's interested in Windows and IoT Security. He loves the blue teaming and plays badminton in his free time.
  - name: "Competition Architect: ISTS"
    appointee: Alison Nakai-Lackey
    image: AlisonBioPic.jpg
    contact: asn5443[at]rit.edu
    description: Alison is a third-year Computing Security student with a minor in Computer Science. Her primary focus is in malware analysis & research. Alison currently works as a defender and malware analyst at a SOC, and was previously the Black Team Logging Lead. Outside of security, she enjoys historical sewing in her free time.
  - name: "Competition Architect: IRSeC & CTF"
    appointee: Jason Howe
    image: JasonBioPic.jpg
    contact: jbh3464[at]rit.edu
    description: Jason is a third year Computing Security student with an affinity to all-nighters and shenanigans. He enjoys red teaming and blue teaming, and working with networking and linux. Will most likely be found with a Monster in the labs at night. In his free time, he likes to workout and enjoy the Outdoors.
  - name: Treasurer
    appointee: Olivia Gallucci
    image: OliviaBioPic.jpg
    contact: gallucci[at]protonmail.com
    description: Olivia is a sophomore in RIT’s Honors Program, double-majoring in Computing Security and Computer Science and minoring in Free and Open Source Software and Free Culture. Olivia’s interests include open-source malware, open-access research, and cybersecurity competitions. She has worked for Open@RIT, Deloitte, and Cyber Defense Magazine. Outside of security, Olivia enjoys sailing, blogging, and reading.
  - name: Secretary
    appointee: Jazmin Morales
    image: JazminBioPic.jpg
    contact: jab5879[at]rit.edu
    description: Jazmin is a second  year Computing Security student with a minor in psychology. Currently interested software security but wants to take on more personal projects to widen her perspective. Outside of security she plays music, fishes and explores restaurant cuisine.
  - name: Tech Lead
    appointee: Max Fusco
    image: MaxBioPic.jpg
    contact: msf9542[at]rit.edu
    description: Max is a third-year computing Security major with a minor in math. He’s interested in pentesting and where ever his personal projects take him.  He doesn’t have any free time but if he did he would sleep.
  - name: Operations Lead
    appointee: Philo Gray
    image: PhiloBioPic.jpg
    contact: rpg4231[at]rit.edu
    description: Philo is a fourth-year Computing Security student interested in hardware and network security. In her free time, she plays games and does film photography.

#-------------------------------
# About Us

about_us_short: >
  <p>
  RITSEC is a student club dedicated to teaching "Security Through Community." RITSEC is dedicated to educating
  and preparing RIT students to compete in security-related competitions, as well as showcasing RIT student talent
  in the current world of security today. Whether you're new to computing security or a veteran, RITSEC has a place for
  you. All of the activities we host to promote this learning can be found on our 'Events' page.
  </p>
about_us_long: >
  RITSEC is a student club dedicated to teaching "Security Through Community." RITSEC is dedicated to educating
  and preparing RIT students to compete in security-related competitions, as well as showcasing RIT student talent
  in the current world of security today. Whether you're new to computing security or a veteran, RITSEC has a place for
  you. All of the activities we host to promote this learning can be found on our 'Events' page.
  <br><br>
  We believe security is for anyone who wants to learn and center our activities around multiple aspects of security.
  This includes live individual and team-based competitions, hands-on training, student run research, and sponsor talks.
  Our security exercises cover a wide variety of areas in computing security, including penetration testing,
  Windows and Linux server hardening,
  web security, network services, and more!

#-------------------------------
# Interest Programs

interest_programs:
  - name: >-
      <a href="https://wicysrit.weebly.com/">WiCyS Student Chapter</a>
    meeting_time: Time TBD, Location GCI or Zoom
    description: >-
      Women in Cybersecurity Student Chapter at RIT is an all-inclusive interest group dedicated to making RIT's computing security community a better environment for women.
      The chapter holds meetings and events for students to come together and share their passion for security while also creating a supportive network.
    leader: Chris Sequeira, Olivia Gallucci, Kayla Hodgsen
  
  - name: Operations Program
    meeting_time: Reach out to Philo with questions! 
    description: >-
      The Ops Program is responsible for supporting our physical infrastructure that is used for competitions, weekly Capture the Flag challenges, and other club programs. 
      Members learn the inner workings of topics like software-defined networking, infrastructure-as-code, and datacenter hardware configuration, all on cloud-scale infrastructure.
    leader: Philo Gray
  
  - name: RITSEC Red Team 
    meeting_time: Keep an eye out for red team recruiting. Reach out to Emmanuel with questions!
    description: >- 
      A group of students and alumni write and use custom tooling to attack competition infrastructure. 
      This provides a challenging learning environment for blue teams.
    leader: Ayobami 'Emmanuel' Adewale

#-------------------------------
# Interest Groups

interest_groups:
  - name: RIT Vulnerability Assessment and Penetration Testing
    meeting_time: Thursdays 7pm ET, Location TBD
    description: >-
      RVAPT on vulnerability assessment and penetration testing. 
      We equally value having a proper offensive security mindset as well as having technical skills. 
    leader: Spencer Roth

  - name: Team Contagion
    meeting_time: Bi-weekly on Wednesday from 6:30pm ET, Location TBD
    description: Team Contagion is the CTF (Capture the Flag) Team of RITSEC. Meetings focus on teaching members and taking deep dives into different CTF categories. Our goal is to develop interest towards CTF’s and create a competitive CTF team that competes at the international level.
    leader: Tenchi Mata, Chandi Kanhai

  - name: Physical Security Interest Group
    meeting_time: Tuesdays 1pm, Location TBD
    description: >-
      Run by Loudon Mehling, physical security IG is all about learning the 
      aspects of physical pentesting, with a primary focus on lockpicking. 
    leader: Loudon Mehling
  
  - name: Reversing Interest Group
    meeting_time: Wednesday 4pm ET, Location TBD
    description: Reversing IG focuses on the low level disassembly and decompilation of software. Meetings will focus on teaching members on the tools and techniques used in the process.
    leader: Ayobami Emmanuel Adewale, Aaron Gdanski

  - name: Incident Response Interest Group
    meeting_time: Tuesday 3pm, Location TBD
    description: IRIG focuses on learning defensive security in modern business security organizations. This is not just purely technical-focused as security organizations have to have non-technical skills because of the need for security policy, presentations, report writing, and more. As such, technical skill and soft skills are equally valued.
    leader: Evan Mikulski
  
  - name: OPS Interest Group
    meeting_time: Time TBD, Location TBD
    description: More info coming soon!
    leader: Malik Hammad

#-------------------------------
# Events
events:
  - name: Weekly Education Meeting
    description: >
      Join us every Friday, 12:00 PM - 2:00 PM for a presentation and hands-on
      lab to learn a new security topic! Labs are generally made up of multiple
      challenges of varying difficulty, and are intended to give members
      practical experience with the topics discussed in the week's presentation.
      Club members can earn points that accumulate over the semester for
      completing challenges. How high up on the leaderboard can YOU make it?
      You can participate in our weekly demos at <a target="_blank"; href="https://flags.ritsec.club">flags.ritsec.club</a>
    image: logo_header.png
  - name: Weekly Research Meeting
    description: >
      Following the education section, RITSEC hosts a research section every
      Friday, 2:00 PM - 4:00 PM. Students are given the opportunity to present on
      security topics that interest them and any current projects they would like
      to share with the club. Please contact the Head of Research to submit a
      presentation.
    image: ritsec_research_logo.png
  - name: <a href="https://www.ists.io">ISTS</a>
    description: >
      The Information Security Talent Search (ISTS) is an annual three-day competition hosted in the early spring at RIT. 
      Every year, competitors from both RIT and colleges around the country are faced with a wide variety of challenges which are designed to cover many facets of the security industry. 
      This includes defensive and offensive capabilities, system administration, software security, networking, programming, and much more! 
      Challenges and activities include a thematic game, Capture the Flag (CTF), King-of-the-Hill (KoTH), policy writing, incident response, and code review—all while defending a completely student-built infrastructure. 
    image: ists21.png
  - name: RITSEC CTF
    description: >
      The RITSEC CTF is a <a href="https://ctftime.org/ctf-wtf/">Jeopardy-style
      CTF</a> hosted online for 60 hours in the late fall. Participation is open
      to all, and registered RIT teams are eligible for prizes! The CTF generally
      focuses on binary/RE, cryptography, forensics, progamming, and web security
      challenges. We welcome beginners and more advanced security friends alike!
    image: ctf2021.png
  - name: IRSeC
    description: >
      The Incident Response Security Competition is our more beginner-friendly
      Red/Blue competition. IRSeC is typically hosted in the early fall at RIT.
      With IRSeC, we aim to provide RIT students with some initial defensive and
      incident response experience. IRSeC also features an entirely student-run
      Red Team comprised of RITSEC members.
    image: irsec20.png
  - name: NSIC
    description: >
      The Networking and Systems Infrastructure Competition (NSIC) is focused on building a corporate network topology from the ground up. 
      Participants work with hardware from multiple vendors, and must work together to configure and deploy software based on business task requirements.
    image: nsic-logo-black.png
